FROM mcr.microsoft.com/dotnet/sdk:3.1 as build
WORKDIR /app
COPY ./sourceBackupPortal/ProjectSourceBackupToolPortal.csproj /app

RUN dotnet restore

COPY ./sourceBackupPortal ./

RUN dotnet publish -c RELEASE -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:3.1

WORKDIR /app

COPY --from=build /app/out .
COPY ./sourceBackupPortal/appsettings.Staging.json /app/hosting.json

EXPOSE 80

ENTRYPOINT ["dotnet", "ProjectSourceBackupToolPortal.dll"]
